<?php
/**
 * Mavenbird Technologies Private Limited
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://mavenbird.com/Mavenbird-Module-License.txt
 *
 * =================================================================
 *
 * @category    Mavenbird
 * @package     Mavenbird_CancelOrder
 * @author      Mavenbird Team
 * @copyright   Copyright (c) 2018-2024 Mavenbird Technologies Private Limited ( http://mavenbird.com )
 * @license     http://mavenbird.com/Mavenbird-Module-License.txt
 */
// phpcs:disable Magento2.Templates.ThisInTemplate
// @codingStandardsIgnoreFile

/** @var \Magento\Sales\Block\Order\History $block */
/** @var \Mavenbird\CancelOrder\Helper\Data $helper */
$helper = $this->helper('Mavenbird\CancelOrder\Helper\Data');
$configEnabled = $helper->isEnabled();
?>
<?php $_orders = $block->getOrders(); ?>
<?= $block->getChildHtml('info') ?>
<?php if ($_orders && count($_orders)) : ?>
    <div class="table-wrapper orders-history">
        <table class="data table table-order-items history" id="my-orders-table">
            <caption class="table-caption"><?= $block->escapeHtml(__('Orders')) ?></caption>
            <thead>
                <tr>
                    <th scope="col" class="col id"><?= $block->escapeHtml(__('Order #')) ?></th>
                    <th scope="col" class="col date"><?= $block->escapeHtml(__('Date')) ?></th>
                    <?= $block->getChildHtml('extra.column.header') ?>
                    <th scope="col" class="col total"><?= $block->escapeHtml(__('Order Total')) ?></th>
                    <th scope="col" class="col status"><?= $block->escapeHtml(__('Status')) ?></th>
                    <th scope="col" class="col actions"><?= $block->escapeHtml(__('Action')) ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($_orders as $_order) : ?>
                    <tr>
                        <td data-th="<?= $block->escapeHtml(__('Order #')) ?>" class="col id"><?= $block->escapeHtml($_order->getRealOrderId()) ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Date')) ?>" class="col date"><?= /* @noEscape */ $block->formatDate($_order->getCreatedAt()) ?></td>
                        <?php $extra = $block->getChildBlock('extra.container'); ?>
                        <?php if ($extra) : ?>
                            <?php $extra->setOrder($_order); ?>
                            <?= $extra->getChildHtml() ?>
                        <?php endif; ?>
                        <td data-th="<?= $block->escapeHtml(__('Order Total')) ?>" class="col total"><?= /* @noEscape */ $_order->formatPrice($_order->getGrandTotal()) ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Status')) ?>" class="col status"><?= $block->escapeHtml($_order->getStatusLabel()) ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Actions')) ?>" class="col actions">
                            <a href="<?= $block->escapeUrl($block->getViewUrl($_order)) ?>" class="action view">
                                <span><?= $block->escapeHtml(__('View Order')) ?></span>
                            </a>
                            <?php if ($this->helper(\Magento\Sales\Helper\Reorder::class)->canReorder($_order->getEntityId())) : ?>
                                <a href="#" data-post='<?= /* @noEscape */
                                $this->helper(\Magento\Framework\Data\Helper\PostHelper::class)
                                    ->getPostData($block->getReorderUrl($_order))
                                ?>' class="action order">
                                    <span><?= $block->escapeHtml(__('Reorder')) ?></span>
                                </a>
                            <?php endif ?>
                            <?php
                                $allowedStatuses = ['pending', 'new'];
                                if ($_order->canCancel() && in_array($_order->getStatus(), $allowedStatuses) && $configEnabled): ?>
                                    <button type="button" class="action primary mavenbird-cancel-btn" id="cancel-order-btn"
                                            data-order-id="<?= $_order->getId() ?>">
                                        <?= __('Cancel Order') ?>
                                    </button>
                                <?php endif; ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml()) : ?>
        <div class="order-products-toolbar toolbar bottom"><?= $block->getPagerHtml() ?></div>
    <?php endif ?>
 <div id="cancel-order-popup" class="mavenbird-popup-overlay" style="display:none;">
            <div class="mavenbird-popup">
                <h3><?= __('Cancel Order # %1', $_order->getIncrementId()) ?></h3>

                <div class="mavenbird-popup-body">
                    <label for="cancel-reason-select"><?= __('Select Reason') ?></label>
                    <select id="cancel-reason-select" class="mavenbird-select">
                        <option value="Ordered by mistake"><?= $block->escapeHtml(__('Ordered by mistake')) ?></option>
                        <option value="Found a better price elsewhere"><?= $block->escapeHtml(__('Found a better price elsewhere')) ?></option>
                        <option value="Delivery time too long"><?= $block->escapeHtml(__('Delivery time too long')) ?></option>
                        <option value="Changed my mind"><?= $block->escapeHtml(__('Changed my mind')) ?></option>
                        <option value="Item no longer needed"><?= $block->escapeHtml(__('Item no longer needed')) ?></option>
                        <option value="Applied wrong payment method"><?= $block->escapeHtml(__('Applied wrong payment method')) ?></option>
                        <option value="Wanted a different product/variant"><?= $block->escapeHtml(__('Wanted a different product/variant')) ?></option>
                        <option value="Placed a duplicate order"><?= $block->escapeHtml(__('Placed a duplicate order')) ?></option>
                        <option value="Seller hasn’t confirmed/shipped yet"><?= $block->escapeHtml(__('Seller hasn’t confirmed/shipped yet')) ?></option>
                        <option value="Other"><?= $block->escapeHtml(__('Other')) ?></option>
                    </select>

                    <div id="cancel-reason-other-box" class="mavenbird-textarea-box" style="display:none;">
                        <textarea id="cancel-reason-other" class="mavenbird-textarea"
                                  placeholder="<?= __('Enter your reason') ?>"></textarea>
                    </div>
                </div>
                <div class="mavenbird-cancel-messages">
                    <?= $block->getChildHtml('messages') ?>
                </div>
                <div class="mavenbird-popup-footer">
                    <button type="button" class="action primary" id="submit-cancel-order">
                        <?= __('Submit') ?>
                    </button>
                    <button type="button" class="action secondary mavenbird-close-popup">
                        <?= __('Close') ?>
                    </button>
                </div>
            </div>
        </div>
     

<script type="text/x-magento-init">
{
    "*": {
        "Mavenbird_CancelOrder/js/cancel-order": {}
    }
}
</script>
<?php else : ?>
    <div class="message info empty"><span><?= $block->escapeHtml($block->getEmptyOrdersMessage()) ?></span></div>
<?php endif ?>
